import http from "node:http";
import fs from "node:fs/promises";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { config } from "./config.mjs";
import { Store } from "./store.mjs";
import { loadCapabilities } from "./capabilities.mjs";
import { TaskManager } from "./task-manager.mjs";
import { ensureInside } from "./fs-utils.mjs";
import { ResearchAgents } from "./research-agents.mjs";
import { ResearchBoards } from "./research-boards.mjs";
import { MathCatClient } from "./mathcat-client.mjs";

const execFileAsync = promisify(execFile);
const store = await new Store(config.runtimeRoot).load();
const capabilities = await loadCapabilities(config.capabilitiesRoot);
const tasks = new TaskManager({ store, config, capabilities });
const researchAgents = await new ResearchAgents(config).load();
const mathcat = new MathCatClient(config.mathcat);
const researchBoards = await new ResearchBoards(config.runtimeRoot, mathcat).load();
function sendJson(res,status,value){const data=JSON.stringify(value);res.writeHead(status,{"content-type":"application/json; charset=utf-8","content-length":Buffer.byteLength(data),"cache-control":"no-store"});res.end(data)}
function fail(res,status,message){sendJson(res,status,{ok:false,error:message})}
async function readBody(req){let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>2_000_000)throw new Error("Request is too large.");chunks.push(chunk)}return chunks.length?JSON.parse(Buffer.concat(chunks).toString("utf8")):{} }
function mime(file){return({".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".md":"text/markdown; charset=utf-8",".tex":"text/plain; charset=utf-8",".bib":"text/plain; charset=utf-8",".sty":"text/plain; charset=utf-8",".log":"text/plain; charset=utf-8",".txt":"text/plain; charset=utf-8",".svg":"image/svg+xml",".woff2":"font/woff2",".woff":"font/woff",".ttf":"font/ttf",".pdf":"application/pdf",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".pptx":"application/vnd.openxmlformats-officedocument.presentationml.presentation",".docx":"application/vnd.openxmlformats-officedocument.wordprocessingml.document",".zip":"application/zip"})[path.extname(file).toLowerCase()]||"application/octet-stream"}
async function serveStatic(res,pathname){const file=ensureInside(config.publicRoot,path.join(config.publicRoot,pathname==="/"?"index.html":pathname.slice(1)));const data=await fs.readFile(file);res.writeHead(200,{"content-type":mime(file),"content-length":data.length});res.end(data)}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||"localhost"}`);const pathname=decodeURIComponent(url.pathname);
if(req.method==="GET"&&pathname==="/api/health"){const mathcatHealth=await mathcat.health().catch(error=>({status:"unavailable",message:error.message}));return sendJson(res,200,{ok:true,service:"math-lab-platform",capabilities:capabilities.length,codexConfigured:Boolean(config.codexBin),mathcat:mathcatHealth})}
if(req.method==="GET"&&pathname==="/api/capabilities")return sendJson(res,200,capabilities.map(({root,skillFile,adapterFile,...item})=>item));
if(req.method==="GET"&&pathname==="/api/research-agents")return sendJson(res,200,await researchAgents.list());
const rbcm=pathname.match(/^\/api\/research-boards\/by-conversation\/([^/]+)$/);if(req.method==="GET"&&rbcm){const board=await researchBoards.viewByConversation(rbcm[1]);return board?sendJson(res,200,board):fail(res,404,"Research board not found.")}
if(req.method==="POST"&&pathname==="/api/research-boards"){const input=await readBody(req);const conversation=store.getConversation(input.conversationId);if(!conversation)return fail(res,404,"Conversation not found.");return sendJson(res,201,await researchBoards.create({conversationId:conversation.id,workspaceId:conversation.workspaceId,agent:input.agent||"mathcat",problem:String(input.problem||conversation.title),title:conversation.title}))}
const rbm=pathname.match(/^\/api\/research-boards\/([^/]+)$/);if(req.method==="GET"&&rbm){const board=await researchBoards.view(rbm[1]);return board?sendJson(res,200,board):fail(res,404,"Research board not found.")}
if(req.method==="PATCH"&&rbm)return sendJson(res,200,await researchBoards.updateProblem(rbm[1],await readBody(req)));
const rbrm=pathname.match(/^\/api\/research-boards\/([^/]+)\/routes$/);if(req.method==="POST"&&rbrm)return sendJson(res,201,await researchBoards.addRoute(rbrm[1],await readBody(req)));
const rbrcm=pathname.match(/^\/api\/research-boards\/([^/]+)\/routes\/([^/]+)\/commands$/);if(req.method==="POST"&&rbrcm){const input=await readBody(req);return sendJson(res,200,await researchBoards.routeCommand(rbrcm[1],rbrcm[2],input.command))}
const rbdm=pathname.match(/^\/api\/research-boards\/([^/]+)\/decisions$/);if(req.method==="POST"&&rbdm)return sendJson(res,201,await researchBoards.addDecision(rbdm[1],await readBody(req)));
const rbdam=pathname.match(/^\/api\/research-boards\/([^/]+)\/decisions\/([^/]+)$/);if(req.method==="POST"&&rbdam){const input=await readBody(req);return sendJson(res,200,await researchBoards.answerDecision(rbdam[1],rbdam[2],input.answer,input.note||""))}
const ram=pathname.match(/^\/api\/research-agents\/([^/]+)\/configure$/);if(req.method==="POST"&&ram){const input=await readBody(req);const result=await researchAgents.configure(ram[1],input.path||null);const conversation=await store.createConversation({workspaceId:null,title:`配置 ${result.name}`});await store.updateConversation(conversation.id,(row)=>{row.configuringResearchAgent=result.found?null:result.id;row.messages.push({id:crypto.randomUUID(),role:"user",content:`首次使用 ${result.name}，请查找本地智能体并完成配置。`,createdAt:new Date().toISOString(),executor:"codex",capabilityId:null});row.messages.push(result.found?{id:crypto.randomUUID(),role:"assistant",content:`已找到并配置 ${result.name}：\n${result.path}\n\n后续选择“研究喵 · ${result.name}”时将通过 Codex CLI 使用该智能体。`,createdAt:new Date().toISOString(),executor:"codex",capabilityId:null}:{id:crypto.randomUUID(),role:"assistant",content:`未在常用位置找到本地 ${result.name}。请选择下一步：`,createdAt:new Date().toISOString(),executor:"codex",capabilityId:null,permission:"workspace-write",choice:{question:`需要如何配置 ${result.name}？`,options:[{label:"从 GitHub 下载并配置",reason:`使用官方仓库 ${result.repo}`,value:`请从 ${result.repo} 下载 ${result.name}，检查项目说明并完成本地配置。`},{label:"手动输入智能体地址",reason:"由我提供已有的本地目录",value:`请提示我输入 ${result.name} 的本地目录地址；我下一条消息会粘贴绝对路径。`}],recommendedIndex:null,recommendationReason:null,selectedIndex:null}});});return sendJson(res,201,{...result,conversationId:conversation.id})}
if(req.method==="GET"&&pathname==="/api/workspaces")return sendJson(res,200,store.listWorkspaces());
if(req.method==="POST"&&pathname==="/api/workspaces")return sendJson(res,201,await store.addWorkspace(await readBody(req)));
const wm=pathname.match(/^\/api\/workspaces\/([^/]+)$/);if(req.method==="DELETE"&&wm){const conversations=store.listConversations().filter(item=>item.workspaceId===wm[1]);if(conversations.some(item=>tasks.getActivity(item.id).running))return fail(res,409,"Cannot remove a workspace while one of its conversations is running.");const removed=await store.deleteWorkspace(wm[1]);await researchBoards.deleteByConversations(removed.conversationIds);return sendJson(res,200,{ok:true,removedConversations:removed.conversationIds.length})}
if(req.method==="GET"&&pathname==="/api/directories"){
  const requested=url.searchParams.get("path");
  if(!requested){const roots=[];for(let code=67;code<=90;code++){const drive=`${String.fromCharCode(code)}:\\`;try{if((await fs.stat(drive)).isDirectory())roots.push({name:drive,path:drive})}catch{}}return sendJson(res,200,{path:null,parent:null,entries:roots})}
  const current=path.resolve(requested);const stat=await fs.stat(current);if(!stat.isDirectory())return fail(res,400,"Path is not a directory.");
  const entries=(await fs.readdir(current,{withFileTypes:true})).filter(item=>item.isDirectory()).map(item=>({name:item.name,path:path.join(current,item.name)})).sort((a,b)=>a.name.localeCompare(b.name,"zh-CN"));
  const parsed=path.parse(current);return sendJson(res,200,{path:current,parent:current===parsed.root?null:path.dirname(current),entries});
}
if(req.method==="POST"&&pathname==="/api/folder-picker"){const result=await execFileAsync("powershell.exe",["-NoLogo","-NoProfile","-STA","-ExecutionPolicy","Bypass","-File",path.join(config.appRoot,"scripts","pick-folder.ps1")],{windowsHide:false,encoding:"utf8",timeout:120_000});return sendJson(res,200,{path:result.stdout.trim()})}
if(req.method==="GET"&&pathname==="/api/conversations")return sendJson(res,200,store.listConversations());
if(req.method==="POST"&&pathname==="/api/conversations")return sendJson(res,201,await store.createConversation(await readBody(req)));
const cm=pathname.match(/^\/api\/conversations\/([^/]+)$/);if(req.method==="GET"&&cm){const row=store.getConversation(cm[1]);return row?sendJson(res,200,row):fail(res,404,"Conversation not found.")}
if(req.method==="DELETE"&&cm){if(tasks.getActivity(cm[1]).running)return fail(res,409,"Cannot remove a running conversation.");await store.deleteConversation(cm[1]);await researchBoards.deleteByConversation(cm[1]);return sendJson(res,200,{ok:true})}
const am=pathname.match(/^\/api\/conversations\/([^/]+)\/activity$/);if(req.method==="GET"&&am)return sendJson(res,200,tasks.getActivity(am[1]));
const cancelm=pathname.match(/^\/api\/conversations\/([^/]+)\/cancel$/);if(req.method==="POST"&&cancelm)return sendJson(res,202,await tasks.cancel(cancelm[1]));
const mm=pathname.match(/^\/api\/conversations\/([^/]+)\/messages$/);if(req.method==="POST"&&mm){const input=await readBody(req);const text=String(input.text||"").trim();if(!text)return fail(res,400,"Message is required.");if(input.executor&&input.executor!=="codex")return fail(res,400,"Only the Codex executor is available.");const currentConversation=store.getConversation(mm[1]);const configuring=currentConversation?.configuringResearchAgent;const manualPath=text.replace(/^["']|["']$/g,"");if(configuring&&/^[A-Za-z]:[\\/]/.test(manualPath)){const result=await researchAgents.configure(configuring,manualPath);await store.updateConversation(mm[1],row=>{row.configuringResearchAgent=null;row.messages.push({id:crypto.randomUUID(),role:"user",content:text,createdAt:new Date().toISOString(),executor:"codex",capabilityId:null});row.messages.push({id:crypto.randomUUID(),role:"assistant",content:`已验证并保存 ${result.name} 地址：\n${result.path}\n\n现在可以返回“研究喵”并选择 ${result.name}。`,createdAt:new Date().toISOString(),executor:"codex",capabilityId:null});});return sendJson(res,202,{ok:true,configured:true})}let researchAgent=null;if(input.capabilityId==="rethlas-research"){researchAgent=await researchAgents.get(input.researchAgent||"mathcat");if(!researchAgent?.configured)return fail(res,409,`${researchAgent?.name||"Research agent"} is not configured.`);await researchBoards.create({conversationId:mm[1],workspaceId:currentConversation?.workspaceId,agent:researchAgent.id,problem:text})}return sendJson(res,202,await tasks.start({conversationId:mm[1],text,executor:"codex",capabilityId:input.capabilityId||null,researchAgent,permission:input.permission==="read-only"?"read-only":"workspace-write"}))}
const chm=pathname.match(/^\/api\/conversations\/([^/]+)\/choices$/);if(req.method==="POST"&&chm){const input=await readBody(req);return sendJson(res,202,await tasks.choose({conversationId:chm[1],messageId:input.messageId,optionIndex:input.optionIndex}))}
if(req.method==="GET"&&pathname==="/api/artifact"){const c=store.getConversation(url.searchParams.get("conversationId"));if(!c)return fail(res,404,"Conversation not found.");const workspace=store.workspaceFor(c);const requested=path.resolve(url.searchParams.get("path")||"");ensureInside(workspace.path,requested);if(!c.messages.some(item=>(item.artifacts||[]).includes(requested)))return fail(res,403,"Artifact is not registered.");const data=await fs.readFile(requested);res.writeHead(200,{"content-type":mime(requested),"content-length":data.length});return res.end(data)}
if(req.method==="GET"&&pathname==="/api/reveal-file"){const c=store.getConversation(url.searchParams.get("conversationId"));if(!c)return fail(res,404,"Conversation not found.");const workspace=store.workspaceFor(c);const input=(url.searchParams.get("path")||"").replace(/^\/(?=[A-Za-z]:[\\/])/,"").replace(/\\_/g,"_");const requested=ensureInside(workspace.path,path.resolve(input));await fs.stat(requested);await execFileAsync("powershell.exe",["-NoLogo","-NoProfile","-STA","-ExecutionPolicy","Bypass","-File",path.join(config.appRoot,"scripts","reveal-file.ps1"),"-LiteralPath",requested],{windowsHide:true,encoding:"utf8",timeout:8_000});return sendJson(res,200,{ok:true,path:requested})}
if(req.method==="GET"&&pathname==="/api/workspace-file"){const c=store.getConversation(url.searchParams.get("conversationId"));if(!c)return fail(res,404,"Conversation not found.");const workspace=store.workspaceFor(c);const input=(url.searchParams.get("path")||"").replace(/^\/(?=[A-Za-z]:[\\/])/,"").replace(/\\_/g,"_");const requested=ensureInside(workspace.path,path.resolve(input));const stat=await fs.stat(requested);if(!stat.isFile())return fail(res,400,"Path is not a file.");const data=await fs.readFile(requested);res.writeHead(200,{"content-type":mime(requested),"content-length":data.length,"content-disposition":`inline; filename*=UTF-8''${encodeURIComponent(path.basename(requested))}`});return res.end(data)}
if(req.method==="GET")return await serveStatic(res,pathname);return fail(res,404,"Not found.")}catch(error){return fail(res,error.code==="ENOENT"?404:500,error.message)}});
server.listen(config.port,config.host,()=>console.log(`Math Lab Platform listening on http://${config.host}:${config.port}/`));
